name: Go matrix

on:
  workflow_dispatch:

jobs:
  go-matrix:
    name: Go matrix
    runs-on: ['ubuntu-latest']
    strategy:
      fail-fast: false
      matrix:
        go-version:
        - 1.16.3
        - 1.16.8
        - 1.17.1

    steps:
    - uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
    - uses: actions/checkout@v2
    - uses: imjasonh/setup-ko@v0.4
    - run: ko deps $(ko publish ./) | grep mod
