name: Manual

on:
  workflow_dispatch:
    inputs:
      image:
        description: foo
        required: true

jobs:
  manual:
    name: Manual
    runs-on: ['windows-latest']

    steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        docker version

        docker build -t ghcr.io/imjasonh/ghatest2/test .
        docker run ghcr.io/imjasonh/ghatest2/test
        echo ${GITHUB_TOKEN} | docker login ghcr.io --username nonsense --password-stdin
        docker push gcr.io/imjasonh/ghatest2/test

        docker pull ${{ github.event.inputs.image }}
        docker run ${{ github.event.inputs.image }}
