name: Manual

on:
  workflow_dispatch:
    inputs:
      image:
        description: foo
        required: true

jobs:
  manual:
    name: Manual
    runs-on: ['windows-latest']

    steps:
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ github.token }}
      run: |
        docker version

        docker pull ${{ github.event.inputs.image }}
        docker run ${{ github.event.inputs.image }}
