name: Manual

on:
  workflow_dispatch:
    inputs:
      image:
        description: image to run
        required: true

jobs:
  manual:
    name: Manual
    runs-on: ['windows-latest']

    steps:
    - shell: bash
      run: |
        docker version

        docker pull ${{ github.event.inputs.image }}
        docker run ${{ github.event.inputs.image }}
