name: Nightly

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 0 * * *'  # every day at midnight

jobs:
  nightly:
    name: Nightly
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4

      - name: Publish nightly release
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          # Create nightly release if it doesn't exist; ignore failure
          gh release create nightly --prerelease --notes "Nightly releases" --title "Nightly releases" || true

          name=$(date +'%Y-%m-%d-%s')-$(git rev-parse HEAD | cut -c 1-8)
          echo release name is ${name}
          ko resolve -f test.yaml > nightly-${name}.yaml
          gh release upload nightly nightly-${name}.yaml
