name: Release

on:
  release:
    types: ['created']

jobs:
  release:
    name: Release
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.3
      - name: Generate and upload release.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag=$(echo ${{ github.ref }} | cut -c11-)  # trim refs/tags/
          ko resolve --bare -f test.yaml -t ${tag} > release.yaml
          gh release upload ${tag} release.yaml
