name: Release

on:
  release:
    types: ['created']

jobs:
  release:
    name: Release
    runs-on: ['ubuntu-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      - uses: imjasonh/setup-ko@v0.3
      - name: Generate and upload release.yaml
        run: |
          ko resolve --bare -f test.yaml > release.yaml
          echo ${{ secrets.GITHUB_TOKEN }} > /tmp/token.txt
          gh auth login --with-token < /tmp/token.txt
          gh release upload ${{ github.ref }} release.yaml
