name: Release

on:
  push:
    branches: ['main']

jobs:
  release:
    name: Release
    runs-on: ['ubuntu-latest']

    env:
      KO_DOCKER_REPO: ko.local
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4

      # publish to docker daemon
      - run: ko publish ./
