name: Windows

on: ['push', 'workflow_dispatch']

jobs:
  windows:
    name: Windows
    runs-on: ['windows-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      #- uses: imjasonh/setup-ko@v0.4
      
      - shell: bash
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          set -ex

          # Install ko
          tag=$(curl -s https://api.github.com/repos/google/ko/releases/latest | jq -r '.tag_name')
          os="Windows"

          echo ${GITHUB_TOKEN} | docker login ghcr.io --username nonsense --password-stdin

          # NOTES:
          # - no sudo
          # - ko.exe
          # - Program Files
          if [[ ! -z ${tag} ]]; then
            echo "Installing ko @ ${tag} for ${os}"
            curl -fsL https://github.com/google/ko/releases/download/${tag}/ko_${tag:1}_${os}_x86_64.tar.gz | tar xzf - -C C:\\Program\ Files\\ ko.exe
          fi

      # publish to docker daemon
      - shell: bash
        env:
          KO_DOCKER_REPO: ghcr.io/imjasonh/ghatest2
        run: |
          img=$(ko.exe publish --platform windows/amd64 ./)
          echo "image is $img"
          docker run $img

      # publish to GHCR
      #- run: docker run $(ko.exe publish ./)
