name: Windows

on: ['workflow_dispatch']

jobs:
  windows:
    name: Windows
    runs-on: ['windows-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2
      - uses: imjasonh/setup-ko@v0.4

      # publish to docker daemon
      - run: docker run $(KO_DOCKER_REPO=ko.local ko publish ./)

      # publish to GHCR
      - run: docker run $(ko publish ./)
