name: Windows

on: ['workflow_dispatch']

jobs:
  windows:
    name: Windows
    runs-on: ['windows-latest']

    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - uses: actions/checkout@v2

      #- uses: imjasonh/setup-ko@v0.4
      
      - shell: bash
        run: |
          set -ex

          # Install ko:
          # - if version is "tip", install from tip of main.
          # - if version is "latest-release", look up latest release.
          # - otherwise, install the specified version.
          tag=$(curl -s https://api.github.com/repos/google/ko/releases/latest | jq -r '.tag_name')

          os=${{ runner.os }}
          if [[ $os == "macOS" ]]; then
            os="Darwin"
          fi

          # NOTES:
          # - no sudo
          # - ko.exe
          if [[ ! -z ${tag} ]]; then
            echo "Installing ko @ ${tag} for ${os}"
            curl -fsL https://github.com/google/ko/releases/download/${tag}/ko_${tag:1}_${os}_x86_64.tar.gz | tar xzf - -C /usr/local/bin ko.exe
          fi

      # publish to docker daemon
      - run: docker run $(KO_DOCKER_REPO=ko.local ko.exe publish ./)

      # publish to GHCR
      #- run: docker run $(ko.exe publish ./)
