name: Windows

on:
  workflow_dispatch:
    inputs:
      image:
        description: image to run
        required: true

jobs:
  windows:
    name: Windows
    runs-on: ['windows-latest']

    steps:
    - run: docker run ${{ github.event.inputs.image }}
