name: Windows

on:
  workflow_dispatch:
    inputs:
      image:
        description: Image to run
        required: true
        default: mcr.microsoft.com/windows/nanoserver:1903

jobs:
  windows:
    name: Windows
    runs-on: ['windows-latest']

    steps:
    - run: |
        docker version
        docker run gcr.io/imjasonh/ghatest2-3b797f3433e868656fc12cc06198c02c@sha256:f0631af760a78fea65ca3633e03bf568c451568bae7f894d250bf9df449df01e

